### ISSUE TITLE
HiGlass v1.3.0 release checklist

### ISSUE THREAD

**Issue by pkerpedjiev** [higlass/higlass#426]
The following items need to be completed before we release `v1.3.0`. Feel free to edit as needed.

## Documentation

 - [ ] Add a reference to the higlass blog in the viewconfig section (Track Data Sources)

## Docker

- [ ] Use higlass-app rather than higlass-website

## Server

 - [ ] Use clodius rather than hgtiles

## Other

 - [ ] Fix Mandelbrot fullscreen example: http://higlass.io/app/?config=X36M4xrtS3iPFCp7cFigUQ

**Comment by flekschas** [comment]
Will be addressed with #428

**Comment by mccalluc** [comment]
We're now up to v1.5.7.
